name: shared_utils
description: Shared utilities for personal Flutter projects
version: 0.0.45-dev.45
homepage: https://github.com/quabynah-bilson/shared_utils/tree/main
publish_to: https://github.com/quabynah-bilson/shared_utils.git

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  feather_icons: ^1.2.0
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.2
  fluttericon: ^2.0.0
  google_fonts: ^4.0.3
  logger: ^1.2.2
  simple_animations: ^5.0.0+3
  sliding_sheet: ^0.5.2
  flutter_staggered_animations: ^1.1.1
  flutter_multi_formatter: ^2.10.2
  lottie: ^2.2.0
  flutter_tabler_icons: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: null
# flutter pub publish --dry-run
