name: shared_utils
description: Shared utilities for personal Flutter projects
version: 0.0.18-dev.18
homepage: https://github.com/quabynah-bilson/shared_utils/tree/main

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  bloc: ^7.0.0
  cached_network_image: ^3.0.0-nullsafety
  equatable: ^2.0.0
  feather_icons: ^1.1.0-nullsafety.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.21.0-nullsafety.0
  fluttericon: ^2.0.0
  google_fonts: ^2.0.0
  logger: ^1.0.0
  simple_animations: ^3.1.1
  sliding_sheet: ^0.5.2
  flutter_staggered_animations: ^1.1.1
  flutter_multi_formatter: ^2.8.0
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: null
# flutter pub publish --dry-run
