name: shared_utils
description: Shared utilities for personal Flutter projects
version: 0.0.27-dev.27
homepage: https://github.com/quabynah-bilson/shared_utils/tree/main

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
  cached_network_image:
  equatable:
  feather_icons:
  flutter_bloc:
  flutter_svg:
  fluttericon:
  google_fonts:
  logger:
  simple_animations:
  sliding_sheet:
  flutter_staggered_animations:
  flutter_multi_formatter:
  lottie:
  tabler_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter: null
# flutter pub publish --dry-run
