name: shared_utils
description: Shared utilities for personal Flutter projects
version: 0.1.0-alpha.15
homepage: https://github.com/quabynah-bilson/shared_utils/tree/main
publish_to: 'none' # https://github.com/quabynah-bilson/shared_utils.git

environment:
  sdk: ^3.0.2
  flutter: '>=3.10.4'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  feather_icons: ^1.2.0
  flutter_bloc: ^8.1.1
  flutter_svg: ^2.0.2
  fluttericon: ^2.0.0
  google_fonts: ^4.0.3
  logger: ^1.2.2
  simple_animations: ^5.0.0+3
  modal_bottom_sheet: ^3.0.0-pre
  flutter_staggered_animations: ^1.1.1
  flutter_multi_formatter: ^2.10.2
  lottie: ^2.2.0
  flutter_tabler_icons: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: null
# flutter pub publish --dry-run
# flutter pub publish